# Generated by Django 3.1.2 on 2022-07-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220722_1752'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedepartment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='employeedepartmentaow',
            unique_together={('employeeDepartment', 'orderStepType')},
        ),
    ]
