const URL_PREFIX = 'http://127.0.0.1:8000/api/v1';

const prependURL = (path: string) => `${URL_PREFIX}${path}`;
export const appendPath = (url: string, path: string) => `${url}${path}`;

export const DOCTORS_PATHS_TYPES = {
  LIST: 'LIST',
  DETAILS: 'DETAILS',
  INFO: 'INFO',
  ADD: 'ADD',
  EDIT_DETAILS: 'EDIT_DETAILS',
  EDIT_INFO: 'EDIT_INFO',
  DELETE_DETAILS: 'DELETE_DETAILS',
  DELETE_INFO: 'DELETE_INFO',
};

const DOCTORS_RELATIVE_PATHS = {
  [DOCTORS_PATHS_TYPES.LIST]: '/doctors/',
  [DOCTORS_PATHS_TYPES.DETAILS]: '/doctors/',
  [DOCTORS_PATHS_TYPES.INFO]: '/doctor_details/',
  [DOCTORS_PATHS_TYPES.ADD]: '/doctors/',
  [DOCTORS_PATHS_TYPES.EDIT_DETAILS]: '/doctors/',
  [DOCTORS_PATHS_TYPES.EDIT_INFO]: '/doctor_details/',
  [DOCTORS_PATHS_TYPES.DELETE_DETAILS]: '/doctors/',
  [DOCTORS_PATHS_TYPES.DELETE_INFO]: '/doctor_details/',
};

export const DOCTOR_URLS = {
  [DOCTORS_PATHS_TYPES.LIST]: prependURL(DOCTORS_RELATIVE_PATHS.LIST),
  [DOCTORS_PATHS_TYPES.DETAILS]: prependURL(DOCTORS_RELATIVE_PATHS.DETAILS),
  [DOCTORS_PATHS_TYPES.INFO]: prependURL(DOCTORS_RELATIVE_PATHS.INFO),
  [DOCTORS_PATHS_TYPES.ADD]: prependURL(DOCTORS_RELATIVE_PATHS.ADD),
  [DOCTORS_PATHS_TYPES.EDIT_DETAILS]: prependURL(DOCTORS_RELATIVE_PATHS.EDIT_DETAILS),
  [DOCTORS_PATHS_TYPES.EDIT_INFO]: prependURL(DOCTORS_RELATIVE_PATHS.EDIT_INFO),
  [DOCTORS_PATHS_TYPES.DELETE_DETAILS]: prependURL(DOCTORS_RELATIVE_PATHS.DELETE_DETAILS),
  [DOCTORS_PATHS_TYPES.DELETE_INFO]: prependURL(DOCTORS_RELATIVE_PATHS.DELETE_INFO),
};

export default { DOCTOR_URLS };
