# Generated by Django 3.1.2 on 2022-07-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstep',
            name='status',
            field=models.TextField(choices=[('ready-for-work', 'Ready for work'), ('currently-in-work', 'Currently in work'), ('finished-working', 'Finished Working')], default='ready-for-work'),
        ),
        migrations.AlterUniqueTogether(
            name='orderstep',
            unique_together={('order', 'stepType'), ('stepType', 'stepOrder')},
        ),
    ]
