# Generated by Django 3.1.2 on 2022-07-22 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20220722_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersteptypegroup',
            options={'ordering': ['name'], 'verbose_name': 'Order Step Type Group', 'verbose_name_plural': 'Order Step Type Groups'},
        ),
        migrations.AlterUniqueTogether(
            name='ordersteptypegroup',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='ordersteptypegroup',
            name='orderStepType',
        ),
        migrations.CreateModel(
            name='OrderStepTypeGroupOrderStepType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('orderStepType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.ordersteptype')),
                ('orderStepTypeGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.ordersteptypegroup')),
                ('updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Step Type Group Order Step Type',
                'verbose_name_plural': 'Order Step Type Group Order Step Types',
                'ordering': ['orderStepTypeGroup', 'orderStepType'],
                'unique_together': {('orderStepTypeGroup', 'orderStepType')},
            },
        ),
    ]
